[superadmin]
user = "adminmuchanga"
password = "lindizahara"

[superadmin1]
user = "adminalberto"
password = "alberto@2024"

[superadmin2]
user = "lumiia@2024"
password = "fecomercio@2024"

[openai]
api_key = "sk-proj-28b8FtH7nfipiWDh9Qb7T3BlbkFJwal12NTw6zeVGN9gu68V"
assistant_id = "asst_c8l3OcC50pWlvrm9Da0esQPn"
